#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton
#: import ScreenManager kivy.uix.screenmanager.ScreenManager

#: import Screen kivy.uix.screenmanager.ScreenManager
#: import main GroceryLoggerApp



<HeaderButton@Button>:
    font_size: 32
    size_hint_y: .1

<MiniButton@Button>:
    font_size: 16
    size_hint: .1, .1

<StandardButton@Button>:
    font_size: 16


    #background_normal: 'grey.jpg'
    #background_down: ''
    #background_color: .88, .88, .88, 1
    size_hint: .2, .1

#############################################################################
<SplashScreen>:


#############################################################################
<ProfileScreen>:
    profile_name_text_input: profile_name
    profile_list: profile_list_view

    HeaderButton:
        text: "Select User Profile"
        pos_hint: {"center_x": .5, "top": 1}

    BoxLayout:
        size_hint: .7,.05
        pos_hint: {"center_x": .5, "top": .85}
        Label:
            text: "Enter Profile Name:"
        TextInput:
            id: profile_name
            multiline: False
            write_tab: False
            focus: True

    BoxLayout:
        size_hint_y: .1
        pos_hint: {"top": .75}
        Button:
            text: "Add New Profile"
            size_hint_x: 15
            on_press: root.create_profile()
        Button:
            text: "Select Profile"
            size_hint_x: 15
            on_press:
                app.root.transition.direction = "left"
                app.root.current = "menu_screen"

    GridLayout:
        cols: 1
        pos_hint: {"top": .65}
        padding: [0,0,0,300]
        ListView:
            id: profile_list_view
            #size: (100, '500dp')
            adapter:
                ListAdapter(data=["Zack","Ollie","Rehan","Aaron"], cls=main.ProfileListButton)

    BoxLayout:
        Button:
            text: "Delete Selected Profile"
            size_hint_y: .05
            on_press: root.delete_profile()
#############################################################################
<MenuScreen>:
    HeaderButton:
        text: "Main Menu"
        pos_hint: {"center_x": .5, "top": 1}
    GridLayout:
        cols: 2
        size_hint: .7, .2
        pos_hint: {"center_x": .5, "top": .6}
        spacing: 50
        Button:
            text: "Add Item"
            pos_hint: {"bottom": .5}
            on_press:
                app.root.transition.direction = "up"
                app.root.current = "additem_screen"
        Button:
            text: "View Food Inventory"
            on_press:
                app.root.transition.direction = "left"
                app.root.current = "inventory_screen"
    GridLayout:
        cols: 1
        size_hint: .2, .1
        pos_hint: {"center_x": .5}
        Button:
            text: "Switch Profile"
            on_press:
                app.root.transition.direction = "right"
                app.root.current = "profile_screen"
#############################################################################
<InventoryScreen>:
    item_list: item_list_view

    FloatLayout:
        StandardButton:
            text: "Back to Main Menu"
            pos_hint: {"top": .9}
            on_press:
                app.root.transition.direction = "right"
                app.root.current = "menu_screen"

        HeaderButton:
            text: "Your Food Inventory"
            pos_hint: {"center_x": .5, "top": 1}

        GridLayout:
            cols: 3
            #padding: 100
            size_hint_y: .1
            pos_hint: {"top": .8}
            Button:
                text: "Item Name"
                #on_press:
                    #app.root.
            Button:
                text: "Expiration Date"
            Button:
                text: "Barcode/UPC Number"


        GridLayout:
            cols: 3
            #[from left,from top,from right,from bottom]
            padding: [0,0,0,300]
            pos_hint: {"top": .7}
            #list of item names
            ListView:
                id: item_list_view
                adapter: ListAdapter(data=["Great Value Milk","Tyson Frozen Chicken","JIF Creamy Peanut Butter","Chipotle Tabasco", "Kraft Cheddar Cheese", "Lay's Sour Cream and Onion Chips", "Great Value 2% Milk"], cls=main.ItemListButton, selection_mode='multiple')
#                adapter: ListAdapter(data=["Great Value 2% Milk                                           12/25/18                                         123412346","Tyson Frozen Chicken","JIF Peanut Butter 40oz","Chipotle Tabasco","Kraft Cheddar Cheese","Lay's Sour Cream and Onion Chips","Great Value 2% Milk","Tyson Frozen Chicken","JIF Peanut Butter 40oz","Chipotle Tabasco","Kraft Cheddar Cheese","Lay's Sour Cream and Onion Chips","Great Value 2% Milk","Tyson Frozen Chicken","JIF Peanut Butter 40oz","Chipotle Tabasco","Kraft Cheddar Cheese","Lay's Sour Cream and Onion Chips"], cls=main.ItemListButton)
            #list of expiration dates
            #ListView:
             #   size_hint: .8,.1
              #  id: item_list_view
              #  adapter: ListAdapter(data=["11/10/18","12/25/18","12/25/18","12/25/18","12/25/18","12/25/18","11/10/18","12/25/18","12/25/18","12/25/18","12/25/18","12/25/18","11/10/18","12/25/18","12/25/18","12/25/18","12/25/18","12/25/18"], cls=main.ProfileListButton)
            #list of barcode numbers
            #ListView:
             #   size_hint: .8,.1
              #  id: item_list_view
               # adapter: ListAdapter(data=["078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871"], cls=main.ProfileListButton)


        MiniButton:
            text: "Delete"
            pos_hint: {"center_x": .2 , "center_y": .1}

        StandardButton:
            id: search
            text: "Search Recipes"
            pos_hint: {"center_x": .38, "center_y": .1}
            on_press:
                root.search_recipes()

        MiniButton:
            text: "Add"
            pos_hint: {"center_x": .56, "center_y": .1}
            on_press:
                app.root.transition.direction = "up"
                app.root.current = "additem_screen"
#############################################################################
<AddItemScreen>:

    FloatLayout:
        StandardButton:
            text: "Back to Inventory"
            pos_hint: {"top": .9}
            on_press:
                app.root.transition.direction = "down"
                app.root.current = "inventory_screen"

        HeaderButton:
            text: "Add Item"
            pos_hint: {"center_x": .5, "top": 1}

        TextInput:
            id: barcode_number
            hint_text: "Scan or Enter Barcode Number"
            write_tab: False
            multiline: False
            pos_hint: {"center_x": .4, "top": .7}
            size_hint: .4,.05

        Button:
            text: "Search"
            pos_hint: {"center_x": .7, "top": .7}
            size_hint: .2,.05
            on_press:
                root.search_item(barcode_number)

        Button:
            text: "Select Expiration Date (optional)"
            pos_hint: {"center_x": .5, "top": .65}
            size_hint: .6,.05
            on_press:
                root.get_date(month, day, year)

#        TextInput:
#            id: month
#            hint_text: '2 Digits for Month'
#            write_tab: False
#            multiline: False
#            pos_hint: {"center_x": .3, "top": .5}
#            size_hint: .2,.05
#
#        TextInput:
#            id: day
#            hint_text: '2 Digits for Day'
#            write_tab: False
#            multiline: False
#            pos_hint: {"center_x": .5, "top": .5}
#            size_hint: .2,.05
#
#        TextInput:
#            id: year
#            hint_text: '4 Digits for Year'
#            write_tab: False
#            multiline: False
#            pos_hint: {"center_x": .7, "top": .5}
#            size_hint: .2,.05

        Spinner:
            id: month
            text: "Select Month"
            pos_hint: {"center_x": .3, "top": .6}
            size_hint: .2,.05
            #values: 'January','February','March','April','May','June','July','August','September','October','November','December'
            values: ['01','02','03','04','05','06','07','08','09','10','11','12']

        Spinner:
            id: day
            text: "Select Day"
            pos_hint: {"center_x": .5, "top": .6}
            size_hint: .2,.05
            values: ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']

        Spinner:
            id: year
            text: "Select Year"
            pos_hint: {"center_x": .7, "top": .6}
            size_hint: .2,.05
            values: ['2018','2019','2020']

#    Button:
#        id: btn
#        text: 'Select Month'
#        pos_hint: {"center_x": .3, "top": .45}
#        on_release: dropdown.open(self)
#        size_hint: .2,.05
#        #height: '48dp'
#
#    Button:
#        id: btn2
#        text: 'Select Day'
#        pos_hint: {"center_x": .5, "top": .45}
#        on_release: dropdown.open(self)
#        size_hint: .2,.05
#        #height: '48dp'
#
#    Button:
#        id: btn3
#        text: 'Select Year'
#        pos_hint: {"center_x": .7, "top": .45}
#        on_release: dropdown.open(self)
#        size_hint: .2,.05
#        #height: '48dp'
#
#    DropDown:
#        id: dropdown
#        #on_parent: self.dismiss()
#        on_select: btn.text = '{}'.format(args[1])
#
#        Button:
#            text: 'First Item'
#            size_hint_y: None
#            height: '48dp'
#            on_release: dropdown.select('First Item','test')
#
#        Button:
#            text: 'Second Item'
#            size_hint_y: None
#            height: '48dp'
#            on_release: dropdown.select('Second Item')
#
#        Button:
#            text: 'Third Item'
#            size_hint_y: None
#            height: '48dp'
#            on_release: dropdown.select('Third Item')


    MiniButton:
        text: "Submit"
        pos_hint: {"center_x": .2 , "center_y": .1}
#        on_press:
#            root.get_date(month, day, year) #send this expiration date to database
#            root.search_item(barcode_number) #send the item information with barcode to database

    MiniButton:
        text: "Other"
        pos_hint: {"center_x": .33, "center_y": .1}

    MiniButton:
        text: "Cancel"
        pos_hint: {"center_x": .46, "center_y": .1}
        on_press:
            app.root.transition.direction = "down"
            app.root.current = "inventory_screen"



