#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton
#: import ScreenManager kivy.uix.screenmanager.ScreenManager
#: import Screen kivy.uix.screenmanager.ScreenManager
#: import ProfileScreen screen
#: import InventoryScreen screen
#: import main GroceryLoggerApp




<ProfileScreen>:
    orientation: "vertical"
    profile_name_text_input: profile_name
    profile_list: profile_list_view
    padding: 10
    spacing: 10

    BoxLayout:
        size_hint_y: None
        height: "30dp"

        Label:
            text: "Enter Profile Name:"
        TextInput:
            id: profile_name

    BoxLayout:
        size_hint_y: None
        height: "100dp"
        Button:
            text: "Create Profile"
            size_hint_x: 15
            on_press: root.create_profile()
        Button:
            text: "Delete"
            size_hint_x: 15
            on_press: root.delete_profile()
        Button:
            text: "Inventory"
            size_hint_x: 15
            on_press:
                root.screen_manager.current = "inventory_screen"

    ListView:
        id: profile_list_view
        adapter:
            ListAdapter(data=["Zack","Ollie","Rehan","Aaron"], cls=main.ProfileListButton)


<BigButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1

    background_normal: 'grey.jpg'
    background_down: ''
    background_color: .88, .88, .88, 1
    size_hint: .7, .7

<MiniButton@Button>:
    font_size: 16
    color: 0, 0, 0, 1

    background_normal: 'grey.jpg'
    background_down: ''
    background_color: .88, .88, .88, 1
    size_hint: .1, .1

<StandardButton@Button>:
    font_size: 16
    color: 0, 0, 0, 1

    background_normal: 'grey.jpg'
    background_down: ''
    background_color: .88, .88, .88, 1
    size_hint: .2, .1

<InventoryScreen>:
    FloatLayout:
        MiniButton:
            text: "Back"
            pos_hint: {"top": 1}
            on_press:
                app.root.current = "profile_screen"

        StandardButton:
            text: "Your Grocery Inventory"
            pos_hint: {"center_x": .5, "top": 1}

        BoxLayout:
            orientation: "horizontal"
            size_hint_x: '.9'
            size_hint_y: '7'
            height: .5
            padding: [100,80,80,100]


            ListView:
                size_hint: .8,.1
                id: profile_list_view
                adapter: ListAdapter(data=["Great Value 2% Milk","Tyson Frozen Chicken","item3","item4","item5","item6",], cls=main.ProfileListButton)
            ListView:
                size_hint: .8,.1
                id: profile_list_view
                adapter: ListAdapter(data=["Great Value 2% Milk","Tyson Frozen Chicken","item3","item4","item5","item6",], cls=main.ProfileListButton)
            ListView:
                size_hint: .8,.1
                id: profile_list_view
                adapter: ListAdapter(data=["Great Value 2% Milk","Tyson Frozen Chicken","item3","item4","item5","item6",], cls=main.ProfileListButton)


        MiniButton:
            text: "Delete"
            pos_hint: {"center_x": .2 , "center_y": .1}

        StandardButton:
            text: "Search Recipes"
            pos_hint: {"center_x": .38, "center_y": .1}

        MiniButton:
            text: "Add"
            pos_hint: {"center_x": .56, "center_y": .1}



