#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton
#: import ScreenManager kivy.uix.screenmanager.ScreenManager
#: import Screen kivy.uix.screenmanager.ScreenManager
#: import main GroceryLoggerApp

<BigButton@Button>:
    font_size: 16



    size_hint: .3, .1

<MiniButton@Button>:
    font_size: 16


    size_hint: .1, .1

<StandardButton@Button>:
    font_size: 16


    #background_normal: 'grey.jpg'
    #background_down: ''
    #background_color: .88, .88, .88, 1
    size_hint: .2, .1

#############################################################################
<ProfileScreen>:
    profile_name_text_input: profile_name
    profile_list: profile_list_view

    BigButton:
        text: "Profile Select"
        pos_hint: {"center_x": .5, "top": 1}

    BoxLayout:
        size_hint: .8,.05
        pos_hint: {"top": .85}
        Label:
            text: "Enter Profile Name:"
        TextInput:
            id: profile_name

    BoxLayout:
        size_hint_y: .1
        pos_hint: {"top": .75}
        Button:
            text: "Create Profile"
            size_hint_x: 15
            on_press: root.create_profile()
        Button:
            text: "Delete"
            size_hint_x: 15
            on_press: root.delete_profile()
        Button:
            text: "Select Profile"
            size_hint_x: 15
            on_press:
                app.root.transition.direction = "left"
                app.root.current = "menu_screen"

    GridLayout:
        cols: 1
        pos_hint: {"top": .65}
        #padding: [100,0,100,100]
        ListView:
            id: profile_list_view
            adapter:
                ListAdapter(data=["Zack","Ollie","Rehan","Aaron"], cls=main.ProfileListButton)
#############################################################################
<MenuScreen>:
    BigButton:
        text: "Main Menu"
        pos_hint: {"center_x": .5, "top": 1}
    GridLayout:
        cols: 2
        size_hint: .5, .2
        pos_hint: {"center_x": .5, "top": .6}
        spacing: 50
        Button:
            text: "Add Item"
            pos_hint: {"bottom": .5}
        Button:
            text: "View Food Inventory"
            on_press:
                app.root.transition.direction = "left"
                app.root.current = "inventory_screen"
    GridLayout:
        cols: 1
        size_hint: .2, .1
        pos_hint: {"center_x": .5}
        Button:
            text: "Logout"
            on_press:
                app.root.transition.direction = "right"
                app.root.current = "profile_screen"
#############################################################################
<InventoryScreen>:
    FloatLayout:
        MiniButton:
            text: "Back"
            pos_hint: {"top": 1}
            on_press:
                app.root.transition.direction = "right"
                app.root.current = "menu_screen"

        BigButton:
            text: "Your Grocery Inventory"
            pos_hint: {"center_x": .5, "top": 1}

        GridLayout:
            cols: 3
            #padding: 100
            size_hint_y: .1
            pos_hint: {"top": .8}
            Button:
                text: "Item Name"
            Button:
                text: "Expiration Date"
            Button:
                text: "Barcode/UPC Number"


        GridLayout:
            cols: 3
            #[from left,from top,from right,from bottom]
            padding: [0,0,0,300]
            pos_hint: {"top": .7}
            #list of item names
            ListView:
                size_hint: .8,.1
                id: profile_list_view
                adapter: ListAdapter(data=["Great Value 2% Milk","Tyson Frozen Chicken","JIF Peanut Butter 40oz","Chipotle Tabasco","Kraft Cheddar Cheese","Lay's Sour Cream and Onion Chips","Great Value 2% Milk","Tyson Frozen Chicken","JIF Peanut Butter 40oz","Chipotle Tabasco","Kraft Cheddar Cheese","Lay's Sour Cream and Onion Chips","Great Value 2% Milk","Tyson Frozen Chicken","JIF Peanut Butter 40oz","Chipotle Tabasco","Kraft Cheddar Cheese","Lay's Sour Cream and Onion Chips"], cls=main.ProfileListButton)
            #list of expiration dates
            ListView:
                size_hint: .8,.1
                id: profile_list_view
                adapter: ListAdapter(data=["11/10/18","12/25/18","12/25/18","12/25/18","12/25/18","12/25/18","11/10/18","12/25/18","12/25/18","12/25/18","12/25/18","12/25/18","11/10/18","12/25/18","12/25/18","12/25/18","12/25/18","12/25/18"], cls=main.ProfileListButton)
            #list of barcode numbers
            ListView:
                size_hint: .8,.1
                id: profile_list_view
                adapter: ListAdapter(data=["078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871","078742022871"], cls=main.ProfileListButton)


        MiniButton:
            text: "Delete"
            pos_hint: {"center_x": .2 , "center_y": .1}

        StandardButton:
            text: "Search Recipes"
            pos_hint: {"center_x": .38, "center_y": .1}

        MiniButton:
            text: "Add"
            pos_hint: {"center_x": .56, "center_y": .1}
#############################################################################


