#: import main ProfileScreen
#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton

InventoryScreen:

<BigButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1

    background_normal: 'grey.jpg'
    background_down: ''
    background_color: .88, .88, .88, 1
    size_hint: .7, .7

<MiniButton@Button>:
    font_size: 16
    color: 0, 0, 0, 1

    background_normal: 'grey.jpg'
    background_down: ''
    background_color: .88, .88, .88, 1
    size_hint: .1, .1

<StandardButton@Button>:
    font_size: 16
    color: 0, 0, 0, 1

    background_normal: 'grey.jpg'
    background_down: ''
    background_color: .88, .88, .88, 1
    size_hint: .2, .1

<FloatLayout>:
    MiniButton:
        text: "Back"
        pos_hint: {"top": 1}
        on_press:
                root.manager.transition.direction = 'left'
                root.manager.transition.duration = 1
                root.manager.current = 'profile_screen'

    StandardButton:
        text: "Your Grocery Inventory"
        pos_hint: {"center_x": .5, "top": 1}

    MiniButton:
        text: "Delete"
        pos_hint: {"center_x": .2 , "center_y": .1}

    StandardButton:
        text: "Search Recipes"
        pos_hint: {"center_x": .38, "center_y": .1}

    MiniButton:
        text: "Add"
        pos_hint: {"center_x": .56, "center_y": .1}

    BigButton:
        text: "Database Table Here"
        pos_hint: {"center_x": .5, "center_y": .5}
        GridLayout:
        cols: 3
            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: "100dp"
                Button:
                    text: "Item Name"
                    on_press: root.create_profile()
                ListView:
                    id: profile_list_view
                    adapter: ListAdapter(data=["Great Value 2% Milk","Tyson Frozen Chicken"], cls=main.ProfileListButton)

            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: "100dp"
                Button:
                    text: "Expiration Date"

                    on_press: root.create_profile()
                ListView:
                    id: profile_list_view
                    adapter: ListAdapter(data=["12/25/2018","1/12/2018"], cls=main.ProfileListButton)

            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: "100dp"
                Button:
                    text: "Barcode/UPC Number"

                    on_press: root.create_profile()
                ListView:
                    id: profile_list_view
                    adapter: ListAdapter(data=["078742022871","023700051172"], cls=main.ProfileListButton)